### ISSUE TITLE
Beginners problem with install

### ISSUE THREAD

**Issue by BertLindeman** [ddemidov/ev3dev-lang-python#1]
On the [README](https://github.com/ddemidov/ev3dev-lang-python/blob/master/README.md) the install is documented as:
```
apt-get install libboost-python-dev
easy_install python-ev3dev
```
In my system `easy_install` was not found.
Had to install ` python-setuptools` 
Running `easy_install -v python-ev3dev` shows:
```
Searching for python-ev3dev
Reading https://pypi.python.org/simple/python-ev3dev/
Found link: https://pypi.python.org/packages/2.7/p/python-ev3dev/python_ev3dev-0.0.1-py2.7-linux-armv7l.egg#md5=2f295fc519f7d03f23cebc3b36bb4444
No local packages or download links found for python-ev3dev
error: Could not find suitable distribution for Requirement.parse('python-ev3dev')
```

Now I am lost :disappointed: 
No hurry and not really important, just curious :smile:

**Comment by ddemidov** [comment]
Thanks for trying this, and sorry for the shitty README. I'll add a note about python-setuptools to the README.

Now, about the error: actually, I had the same problem on my brick. The installation goes flawlessly on the brickstrap image, but gives me the error on the brick itself. What worked for me on the brick is
```
easy_install https://pypi.python.org/packages/2.7/p/python-ev3dev/python_ev3dev-0.0.1-py2.7-linux-armv7l.egg#md5=2f295fc519f7d03f23cebc3b36bb4444
```
This also gives an error, but the egg is installed and is useable nevertheless. I have to admit I don't have much experience with python setup tools.

**Comment by BertLindeman** [comment]
Thanks Dennis,

I did `easy_install -v https://pypi.python.org/packages/2.7/p/python-ev3dev/python_ev3dev-0.0.1-py2.7-linux-armv7l.egg#md5=2f295fc519f7d03f23cebc3b36bb4444` 
and that showed:

```
Downloading https://pypi.python.org/packages/2.7/p/python-ev3dev/python_ev3dev-0.0.1-py2.7-linux-armv7l.egg#md5=2f295fc519f7d03f23cebc3b36bb4444
Validating md5 checksum for /tmp/easy_install-yRXnFI/python_ev3dev-0.0.1-py2.7-linux-armv7l.egg
Processing python_ev3dev-0.0.1-py2.7-linux-armv7l.egg
Removing /usr/local/lib/python2.7/dist-packages/python_ev3dev-0.0.1-py2.7-linux-armv7l.egg
Moving python_ev3dev-0.0.1-py2.7-linux-armv7l.egg to /usr/local/lib/python2.7/dist-packages
python-ev3dev 0.0.1 is already the active version in easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/python_ev3dev-0.0.1-py2.7-linux-armv7l.egg
Processing dependencies for python-ev3dev==0.0.1
Searching for python-ev3dev==0.0.1
Reading https://pypi.python.org/simple/python-ev3dev/
Found link: https://pypi.python.org/packages/2.7/p/python-ev3dev/python_ev3dev-0.0.1-py2.7-linux-armv7l.egg#md5=2f295fc519f7d03f23cebc3b36bb4444
No local packages or download links found for python-ev3dev==0.0.1
error: Could not find suitable distribution for Requirement.parse('python-ev3dev==0.0.1')
```

So the egg *is* installed.
Ignoring the error for now.
Is the next step to run the  `setup.py` from the `ev3dev-lang-python-master` download?

>  I have to admit I don't have much experience with python setup tools.
So in this we are at an equal level :grin:

**Comment by ddemidov** [comment]
> Is the next step to run the setup.py from the ev3dev-lang-python-master download?

The module should be useable at this point. You can try something like
~~~{.py}
$ python
>>> import ev3dev
>>> ev3dev.sound.beep()
~~~
to check this. You don't need to run the setup.py, as that is only needed to create the binary egg you already have on your system.

Another option would be to compile the module on the brickstrap image:
~~~{.sh}
cd ev3dev-lang/python
mkdir build
cd build
cmake .. # this requires apt-get install cmake
make
~~~
Then just copy the resulting ev3dev.so to your project dir on the brick. This way you don't need to use easy_install.

**Comment by BertLindeman** [comment]
Thanks for the explanation, Dennis. 
You helped me prove the beep works.

I am missing the next step: how to use the demo's.
Let me ponder on this for a few days.

**Comment by ddemidov** [comment]
The demos are executable scripts. You can copy them to your brick and run them. For example, either
```
$ ./demo_remote_control.py
```
or
```
python demo_remote_control.py
```
will work. Another nice possibility is launching ipython notebook on the brick and using a browser on your computer to do some interactive experiments. Here is a nice example of this (not mine): http://robotsquare.com/2014/06/12/linux-ev3.

**Comment by BertLindeman** [comment]
Robotsquare from Laurens Valk is good.

iPython looks nice, will try.

I will look into that later. My feeling is that the current kernel is not so stable on

**Comment by ddemidov** [comment]
I think the problem with installation is due to difference between reported architectures on brickstrap and on the brick. See ev3dev/brickstrap#2.

**Comment by ddemidov** [comment]
@BertLindeman, 02b52b4b545657f7beb6d1e76489af8b97ba32be solves the problem for me. Can you check if this is the case for you as well?

**Comment by BertLindeman** [comment]
Confirmed Denis.
Ran `easy_install -v python-ev3dev`

Result:

```
Searching for python-ev3dev
Reading https://pypi.python.org/simple/python-ev3dev/
Found link: https://pypi.python.org/packages/2.7/p/python-ev3dev/python_ev3dev-0.0.1-py2.7-linux-armv5tejl.egg#md5=fd6c5cc3d5c42e0dc9d86cf0e9558220
Found link: https://pypi.python.org/packages/2.7/p/python-ev3dev/python_ev3dev-0.0.2-py2.7-linux-armv5tejl.egg#md5=fd5d5cabb0ca1f2c037007bebae579ca
Best match: python-ev3dev 0.0.2
Downloading https://pypi.python.org/packages/2.7/p/python-ev3dev/python_ev3dev-0.0.2-py2.7-linux-armv5tejl.egg#md5=fd5d5cabb0ca1f2c037007bebae579ca
Validating md5 checksum for /tmp/easy_install-ioI0G1/python_ev3dev-0.0.2-py2.7-linux-armv5tejl.egg
Processing python_ev3dev-0.0.2-py2.7-linux-armv5tejl.egg
Moving python_ev3dev-0.0.2-py2.7-linux-armv5tejl.egg to /usr/local/lib/python2.7/dist-packages
Removing python-ev3dev 0.0.1 from easy-install.pth file
Adding python-ev3dev 0.0.2 to easy-install.pth file
Saving /usr/local/lib/python2.7/dist-packages/easy-install.pth

Installed /usr/local/lib/python2.7/dist-packages/python_ev3dev-0.0.2-py2.7-linux-armv5tejl.egg
Processing dependencies for python-ev3dev
Finished processing dependencies for python-ev3dev
```

No problem what-so-ever :smiley: 

Thanks and closing
