### ISSUE TITLE
use run_timed() in mindstorms_widgets.py for on_for_seconds

### ISSUE THREAD

**Issue by ensonic** [ddemidov/ev3dev-lang-python#10]
white reading mindstorms_widgets.py to learn about the api and looking at dir(ev3dev.large_motor(ev3dev.OUTPUT_B)) I was wondering if the code in

https://github.com/ddemidov/ev3dev-lang-python/blob/master/demo/mindstorms_widgets.py#L128-L133

should be

    self.motor['left'].run_timed(time_sp = int(seconds * 1000))
    self.motor['right'].run_timed(time_sp = int(seconds * 1000))

This needs speed_regulation_enabled="on" as well. If there is a reason for not using it, maybe we can add a comment that point to the issue. If it is a good idea I'll send a PR.

Please note that run_timed() is 'featured' at the end of the README.rst.

**Comment by ddemidov** [comment]
@dandrus-ev3 was trying to model the API of programming bricks of the stock software with this demo (see #7). Possible reason for his choice of `run_forever` vs `run_timed` could be the fact that `run_timed` returns immediately, and Dan wanted it to be a blocking call, in the same way it works in LEGO software. This probably could be done with `run_timed` followed by a sleep, but I am not sure the change worths it.

In this class, Dan sets up the motor attributes by calling [_set_motor_attribs](https://github.com/ddemidov/ev3dev-lang-python/blob/6d1076e009efab0596e6072a6cbe39981addcf66/demo/mindstorms_widgets.py#L268-L270) before calling `_move()`. That is responsible for setting speed regulation and choosing `speed_sp` vs `duty_cycle_sp`.

`run_timed()` can take kwargs, as any of the motor commands.

**Comment by ensonic** [comment]
Thanks for the explanation.
