### ISSUE TITLE
Can't set motor position

### ISSUE THREAD

**Issue by antonvh** [ddemidov/ev3dev-lang-python#12]
I got this on a RPi with brickpi:
```
>>> import ev3dev
>>> m = ev3dev.motor(ev3dev.OUTPUT_A)
>>> m.connected
True
>>> m.position
-2
>>> m.position = 0
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: /sys/class/tacho-motor/motor0/position: No such device
>>> 
```

Other setters seem not to work either:
```
>>> m.set(stop_command='brake')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_ev3dev-0.2.2.post1-py2.7-linux-armv6l.egg/ev3dev/__init__.py", line 154, in batch_set
    setattr(device, key, attr[key])
RuntimeError: /sys/class/tacho-motor/motor0/stop_command: No such device
```

**Comment by ddemidov** [comment]
Can you please show the output of `ls /sys/class/tacho-motor/motor0` on your system? Also, I'd like to see the result of `ls -i /sys/class/tacho-motor/motor0` before and after you run the first script above (the one that touches motor position).

**Comment by antonvh** [comment]
I humbly apologise for the first one: I made a port mistake. The motor was connected to port D, not A. m.connect does not seem to give accurate results on a BrickPi. With the right port, `m.position=0` works fine. Still the brake command doesn't seem to be supported.

Before:
```
anton@ev3dev-rpi1:~$ ls /sys/class/tacho-motor/motor0
command        duty_cycle        port_name     speed             stop_command
commands       duty_cycle_sp     position      speed_pid         stop_commands
count_per_rot  encoder_polarity  position_sp   speed_regulation  subsystem
device         hold_pid          ramp_down_sp  speed_sp          time_sp
driver_name    polarity          ramp_up_sp    state             uevent
anton@ev3dev-rpi1:~$ ls -i /sys/class/tacho-motor/motor0
7892 command           7896 polarity          7888 speed_sp
7891 commands          7881 port_name         7883 state
7884 count_per_rot     7882 position          7895 stop_command
7878 device            7890 position_sp       7894 stop_commands
7880 driver_name       7899 ramp_down_sp      7877 subsystem
7885 duty_cycle        7898 ramp_up_sp        7889 time_sp
7887 duty_cycle_sp     7886 speed             7876 uevent
7897 encoder_polarity  7900 speed_pid
7904 hold_pid          7893 speed_regulation
anton@ev3dev-rpi1:~$ 
```

And after:
```
anton@ev3dev-rpi1:~$ ls -i /sys/class/tacho-motor/motor0
7892 command           7896 polarity          7888 speed_sp
7891 commands          7881 port_name         7883 state
7884 count_per_rot     7882 position          7895 stop_command
7878 device            7890 position_sp       7894 stop_commands
7880 driver_name       7899 ramp_down_sp      7877 subsystem
7885 duty_cycle        7898 ramp_up_sp        7889 time_sp
7887 duty_cycle_sp     7886 speed             7876 uevent
7897 encoder_polarity  7900 speed_pid
7904 hold_pid          7893 speed_regulation
```

Still the stop_command is all weird:
```
>>> m = ev3dev.motor(ev3dev.OUTPUT_D)
>>> m.position
0
>>> m.position
-88
>>> m.position
-109
>>> m.set(stop_command='brake')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/python_ev3dev-0.2.2.post1-py2.7-linux-armv6l.egg/ev3dev/__init__.py", line 154, in batch_set
    setattr(device, key, attr[key])
RuntimeError: Invalid argument
```

**Comment by ddemidov** [comment]
It looks like the motor does not support the `brake` command. What is the output of `m.stop_commands`?

**Comment by antonvh** [comment]
Thanks! This helps. I didn't know I could check if a command was available before using it. I want to write universal code that is usable on the BrickPi and Ev3. I supposed Ev3 commands would be emulated on ev3dev, but apparantly they aren't. This clears up a lot. Do you want me to help write docs about this? Update the wiki?
```
>>> m.stop_commands
['coast']
```

**Comment by ddemidov** [comment]
Any help is appreciated! The python specific help is generated automatically from the README.rst file and the docstrings that are unfortunately specified via boost.python code [here](https://github.com/ddemidov/ev3dev-lang-python/blob/master/ev3dev/pyev3dev.cpp#L571). But may be a better idea would be to make a pull request to update the generic documentation on the [main site](http://www.ev3dev.org/docs/).

By the way, @dlech, is `taho-motor` supposed to provide only `coast` stop command under rpi?

**Comment by dlech** [comment]
The BrickPi is a bit limited compared to the same things on the EV3. Not supporting `brake` is one of them. These things could be fixed, but it would require writing new firmware for the BrickPi.

**Comment by ddemidov** [comment]
Can this be closed?
