### ISSUE TITLE
float int parameter woes

### ISSUE THREAD

**Issue by ensonic** [ddemidov/ev3dev-lang-python#18]
repro:

```
import ev3dev
m = ev3dev.large_motor(ev3dev.OUTPUT_B)
m.run_forever(speed_regulation_enabled='on', speed_sp=100.7)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ev3dev/__init__.py", line 169, in motor_run_forever
    setattr(self, key, attr[key])
Boost.Python.ArgumentError: Python argument types in
    None.None(large_motor, float)
did not match C++ signature:
    None(ev3dev::motor {lvalue}, int)
```

When passing an int value it works.

**Comment by ddemidov** [comment]
For now it would be easier to deal with this on user side with an explicit conversion. I can not change the signature of c++ function. Pure python bindings should be better

**Comment by ensonic** [comment]
Yeah, maybe that just another lessons learned and a + for pure-python. If you write python, you don't expect that you have to manuallyl convert floats to ints. Also there error message contains quite some clutter (e.g. None.None() va. None()) that I don't understand - not sure if that is 'fixable'.

**Comment by antonvh** [comment]
I ran into the same problem, that's why I'm working with @rhempel on pure python bindings. Your welcome to contribute. I hope to make some major progress this weekend.

**Comment by ddemidov** [comment]
This actually can be solved by wrapping the original C++ method into a python one (similar to [this](https://github.com/ddemidov/ev3dev-lang-python/blob/6278794b2191ef3a0eb3a1551f8c984e425f76da/ev3dev/__init__.py#L248-L254)), but since we decided to move to pure python anyway, I say lets just wait when that is ready.

**Comment by ddemidov** [comment]
On the second thought (or third, actually), this is too cumbersome to implement on the library side. Either each `set_*` method that should take an int value should provide an explicit overload for floats on C++ side of things, or each of the corresponding properties in python should be wrapped as in the above comment.

**Comment by ddemidov** [comment]
It was actually very easy to fix. b57ba6a does the trick.

**Comment by ensonic** [comment]
Wow. Thanks a lot!
