### ISSUE TITLE
sensors not recognized

### ISSUE THREAD

**Issue by win-n** [ddemidov/ev3dev-lang-python#2]
I am using a ev3dev version build from ev3dev-jessie-2015-02-24.img By working throug the example "track-line.py", I realized that the color sensor is not recognized. 
( cs = color_sensor()
  cs.connected()
  -> false )
On the brickman display I can browse the sensors and here it is present an recognized correctly.
The same is true for the ultrasonic sensor, which is the only other sensor I presently have. 
Does anyone know how to solve this problem?

**Comment by ddemidov** [comment]
I have just upgraded my ev3 to the latest kernel, and I can reproduce the issue. I'll try to track it down in the coming days. Thanks for the report!

**Comment by ddemidov** [comment]
ev3dev/ev3dev-lang#45 fixed the issue in the c++ library that the python bindings are based on. You don't have to wait for the PR to be merged though; I have uploaded the updated egg to pypi. It should work for you after
```
sudo easy_install python-ev3dev
```

**Comment by win-n** [comment]
@ddemidov: Your solution does not work for me, but a workaround is:
cs=sensor(INPUT_*, ) 
cs.connected()
->true

  cs=sensor(INPUT_*, lego_ev3_uart_29)
bzw
  cs=sensor(INPUT_*, 'lego-ev3-uart-29') 
does not work. In other words, I do not know the propper syntax for the sensor type.

**Comment by ddemidov** [comment]
`sensor` is a generic sensor class, so you have to provide port number to create it. Can you try if
```py
cs = color_sensor()
cs.connected     # note the lack of '()'. properties are proper properties in ev3dev 0.0.4.

us = ultrasonic_sensor()
us.connected
```
works for you? I have uploaded ev3dev-0.0.4 to pypi a couple of days ago, so you might want to update it before this.

**Comment by win-n** [comment]
cs = color_sensor()
cs.connected
-> <bound method color_sensor.connected of <ev3dev.color_sensor object at 0xb69f4e40>>

cs.connected()
-> false

**Comment by ddemidov** [comment]
Looks like you have old version of ev3dev. Can you please show me the output of 
```
sudo easy_install python-ev3dev
```
? And even before that, what is the output of
```
cat /sys/class/lego-sensor/*/driver_name
```
?

**Comment by win-n** [comment]
cat /sys/class/lego-sensor/*/driver_name
$ lego-ev3-uart-29

of course I did the easy_install comand before going on with the python script ...

**Comment by ddemidov** [comment]
But what version did it report installed? From you output above it definitely does not look like the current one.

**Comment by ddemidov** [comment]
This is what I see on my system:
```
>>> from ev3dev import *
>>> cs = color_sensor()
>>> cs.port_name
'in3'
>>> cs.driver_name
'lego-ev3-uart-29'
>>> cs.connected
True
>>> 
```

**Comment by win-n** [comment]
$ sudo easy_install python-ev3dev

output: 
Searching for python-ev3dev
Best match: python-ev3dev 0.0.3.post4
Processing python_ev3dev-0.0.3.post4-py2.7-linux-armv5tejl.egg
python-ev3dev 0.0.3.post4 is already the active version in easy-install.pth

Using /usr/local/lib/python2.7/dist-packages/python_ev3dev-0.0.3.post4-py2.7-linux-armv5tejl.egg
Processing dependencies for python-ev3dev
Finished processing dependencies for python-ev3dev

You are right, it does not look like version 0.0.4. But I did a full system update before...

**Comment by ddemidov** [comment]
does your ev3 have internet connection? You can also download the egg from [this page](https://pypi.python.org/pypi?:action=files&name=python-ev3dev&version=0.0.4) manually and then do
```
sudo easy_install python_ev3dev-0.0.4-py2.7-linux-armv5tejl.egg
```

**Comment by win-n** [comment]
Thanks a lot!

$ sudo easy_install https://pypi.python.org/packages/2.7/p/python-ev3dev/python_ev3dev-0.0.4-py2.7-linux-armv5tejl.egg

did the job. Now everything is like you said.

**Comment by ddemidov** [comment]
Good to know, and thanks again for reporting this!
