### ISSUE TITLE
Auto-drive not working

### ISSUE THREAD

**Issue by NielsAMG** [ddemidov/ev3dev-lang-python#20]
After the EV3-Brick booted, I type the following: sudo apt-get install libboost-python1.55.0 python-setuptools python-pil
after that: sudo  easy_install -U python-ev3dev
and then Python2.7 for the Python shell

That was succesful but then I've tried these commands:
>>> import ev3dev
>>> m = ev3dev.LargeMotor('outA')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'LargeMotor'
>>> m.connected
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'm' is not defined
>>> m.run_timed(time_sp=3000, duty_cycle_sp=75)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'm' is not defined

Why is this? How can I get the motors to run?

**Comment by ddemidov** [comment]
I am sorry, this repo has been outdated in favor of @rhempel's https://github.com/rhempel/ev3dev-lang-python. It is no longer supported and will not work with the recent ev3dev kernels.

You can easily update the demo to work with Ralph's bindings though. The only change should be importing from `ev3dev.auto` instead of `ev3dev`:
```py
from ev3dev.auto import *
```
and also you need to define the `steering` function yourself, as it is no longer provided:
```py
def steering(direction, power=100):
    """
    Computes how fast each motor in a pair should turn to achieve the
    specified steering.
    Input:
        direction [-100, 100]:
            * -100 means turn left as fast as possible,
            *  0   means drive in a straight line, and
            *  100 means turn right as fast as possible.
        power: the power that should be applied to the outmost motor (the one
            rotating faster). The power of the other motor will be computed
            automatically.
    Output:
        a tuple of power values for a pair of motors.
    Example::
        for (motor, power) in zip((left_motor, right_motor), steering(50, 900)):
            motor.run_forever(speed_sp=power)
    """

    pl = power
    pr = power
    s = (50 - abs(float(direction))) / 50

    if direction >= 0:
        pr *= s
    else:
        pl *= s

    return (int(pl), int(pr))
```

**Comment by ddemidov** [comment]
Actually, the auto-drive.py has been ported to the new bindings: https://github.com/rhempel/ev3dev-lang-python/blob/master/demo/auto-drive.py
