### ISSUE TITLE
Attribute from Colorsensor 

### ISSUE THREAD

**Issue by NielsAMG** [ddemidov/ev3dev-lang-python#21]
What attribute has the color sensor?

**Comment by ddemidov** [comment]
You should open subsequent issues at https://github.com/rhempel/ev3dev-lang-python.

Color sensor inherits its attributes from [Sensor](http://python-ev3dev.readthedocs.org/en/latest/?badge=latest#ev3dev.ev3.Sensor). And there is a page on color-sensor-specific modes at ev3dev.org: http://www.ev3dev.org/docs/sensors/lego-ev3-color-sensor/.
