### ISSUE TITLE
Ps4 Controller Bug

### ISSUE THREAD

**Issue by NielsAMG** [ddemidov/ev3dev-lang-python#23]
If I print the events Form the controller allthing is great, but the two Joysticks dont work. All the other buttons work.

**Comment by antonvh** [comment]
Please stop reporting issues in this repo. @ddemidov Can you lock it or delete it? 

Please go to: https://github.com/rhempel/ev3dev-lang-python

I wrote a tutorial here. It includes one button and one stick.

http://www.ev3dev.org/docs/tutorials/using-ps3-sixaxis/

Be sure to share your project.

**Comment by ddemidov** [comment]
@antonvh, the only thing I can do is remove the issues tab completely. I did not want to do this to keep the old issues available, but I guess there is not much value at this point anyway. I'll do it now.
