### ISSUE TITLE
How To Create Python-EV3Dev Scripts using IDE on External Computer

### ISSUE THREAD

**Issue by markovian72** [ddemidov/ev3dev-lang-python#6]
Hi,

I was able to install python-ev3dev onto a Lego EV3 Brick and run commands from the python command prompt and scripts created using nano.

However, now I would like to be able to write scripts using an IDE (like Spyder or PyCharm) on my laptop (running Linux Mint 17.2 64 Bit). Then I would plan to transfer the scripts to the EV3 using scp or sftp.

So far I've done the following on my Linux Mint 17.2 Computer:
1. installed the latest Lego Linux Drivers DKMS
`$ sudo dpkg -i lego-modules_3.0.1_all.deb`
2. installed the python language binding dependencies for ev3dev
`$ sudo apt-get install libboost-python1.55.0 python-setuptools python-pil`
3. tried installing python-ev3dev using easy_install
`$ sudo easy_install -U python-ev3dev`
`$ No local packages or download links found for python-ev3dev`
`$ error: Could not find suitable distribution for Requirement.parse('python-ev3dev')`
4. tried installing python-ev3dev using egg file
`$ sudo easy_install python_ev3dev-0.2.1.post8-py2.7-linux-armv5tejl.egg `
`$ error: Could not find suitable distribution for Requirement.parse('python-ev3dev==0.2.1.post8')`

I think what I need to do is to compile python-ev3dev for my architecture (amd64), since the current stuff is all compiled for ARM, but am not sure what files I need to start with and the proper commands to make & install python-ev3dev. 

Any advice would be appreciated. Thanks.

**Comment by ddemidov** [comment]
You are almost there :). Indeed, you need to install the package from source. Right now, this should work for step 3:
```
$ git clone --recursive https://github.com/ev3dev/ev3dev-lang.git
$ cd ./ev3dev-lang/python
$ sudo easy_install setup.py install
```
Also, I don't think the step 1 is necessary, unless you want to actually connect lego devices to your laptop.

I'll see if it is possible to upload both binary and source eggs to PyPI. Then I hope it should be possible to `sudo easy_install -U python-ev3dev` both on the ev3 and a host computer.

**Comment by ddemidov** [comment]
I've uploaded source tarball and binary egg to pypi. `sudo easy_install -U python-ev3dev` should work everywhere now.

**Comment by markovian72** [comment]
Initially, I still wasn't able to install python-ev3dev because I didn't have the required development library installed. So running easy_install resulted in an error that "boost/python.hpp" couldn't be found.

After some searching, I discovered that the libboost development library needed to be installed:
`sudo apt-get install libboost-python1.55-dev`

After installing this development library I successfully install python-pydev:
`sudo easy_install -U python-ev3dev`

You might want to add this as an optional dependency in the instruction for others that may want to install python-pydev on an external computer.

Thanks again for your support & creating the python-pydev library1

**Comment by ddemidov** [comment]
I've updated the README, thanks for noting this!
