### ISSUE TITLE
Make the bindings compatible with (and create binary package for) Brick Pi

### ISSUE THREAD

**Issue by ddemidov** [ddemidov/ev3dev-lang-python#8]
The one difference between in ev3 and rpi images should be port names. From @dlech on IRC:

> you will need to make the port names "tty1:in1" instead of just "in1"

**Comment by ddemidov** [comment]
Actually, the port names are `ttyAMA0:xxx`

**Comment by Ho33e5** [comment]
Confirming that on rpi1, everything seems to work great with `ttyAMA0:xxx` port names

**Comment by dlech** [comment]
Another difference is that there is not autodetection with birckpi. The motor ports are all set to ev3 large motor by default, but sensors must be configured manually using the lego-port class.

**Comment by ddemidov** [comment]
@Ho33e5, @dlech, could either of you tell me what is the output of `uname -m` on rpi? Just to make sure I wont run into ev3dev/brickstrap#2 again.

**Comment by ddemidov** [comment]
ref ev3dev/ev3dev#369

**Comment by dlech** [comment]
Yes, IIRC, qemu does not have exact matches, so you will have the same issue.

RPi2 is `armv7l`

Don't have RPi1 on a the moment, but I am pretty sure it is `armv6l`

**Comment by ddemidov** [comment]
I wonder how much faster is RPi w.r.t. EV3? May be it should be possible to just compile the package from source tarball on the fly with `easy_install -U python-ev3dev`. Port names would still be wrong, so one would need to provide the names explicitly as strings:
```py
from ev3dev import *
m = large_motor('ttyAMA0:outA')
```

**Comment by BertLindeman** [comment]
On my rpi-B+:
```
ev3dev-rpi:~# uname -m
armv6l
```

**Comment by dlech** [comment]
The RPi is significantly faster (and lots more memory) so compiling on the fly should be OK.

**Comment by ddemidov** [comment]
The source package has been on pypi for some time, so it should be possible to test right now. I'll try to prepare binaries anyway.

**Comment by Ho33e5** [comment]
On my rpi1-B:
```
carotte@lapinot:~$ uname -m
armv6l
```

**Comment by ddemidov** [comment]
> Compiling on-the-fly takes something like 5-10min on mine (but it is acceptable)!

Does it work afterwards?

**Comment by ddemidov** [comment]
@Ho33e5, I've uploaded binary eggs for rpi image to pypi (both for python2 and python3). You should be able to install those with `easy_install -U python-ev3dev`/`easy_install3 -U python-ev3dev` (and it should be much faster than 5-10 minutes). Please let me know if you are able to install and use the egg(s). Something like this should work:
```py
>>> from ev3dev import *
>>> m = large_motor(OUTPUT_A)
>>> m.connected
True
```

Note that we don't provide a `lego_port` class in the unified bindings yet (ref ev3dev/ev3dev-lang#89, ping @WasabiFan), so you would have to configure sensors outside of python.

**Comment by Ho33e5** [comment]
@ddemidov The binary eggs do install well and the code works (I only have nxt motors so I replaced `large_motor` with `motor`). Great!

**Comment by ddemidov** [comment]
Thanks for testing!
